import {
    SpinMissionTargets,
    TargetBannedKillMethods,
    MissionSpinOptions,
    TargetUniqueKills,
    Mission,
    MissionPoolOptions,
    SeasonPoolSelected,
    MissionDisguises,
} from "@/types";

// Global
export const weapons = [
    "pistol",
    "sniper_rifle",
    "assault_rifle",
    "smg",
    "shotgun",
    "explosive",
];
export const weaponsWithModifiers = [
    "pistol",
    "silenced_pistol",
    "loud_pistol",
    "sniper_rifle",
    "silenced_sniper_rifle",
    "loud_sniper_rifle",
    "assault_rifle",
    "silenced_assault_rifle",
    "loud_assault_rifle",
    "smg",
    "silenced_smg",
    "loud_smg",
    "shotgun",
    "silenced_shotgun",
    "loud_shotgun",
    "remote_explosive",
    "loud_explosive",
    "impact_explosive",
];
export const weaponModifierPrefix = ["loud_", "silenced_", ""];
export const explosiveModifierPrefix = ["remote_", "loud_", "impact_"];
export const pistolKillMethodList = [
    "loud_pistol",
    "pistol",
    "silenced_pistol",
];
export const smgKillMethodList = ["loud_smg", "smg", "silenced_smg"];
export const assaultRifleKillMethodList = [
    "loud_assault_rifle",
    "assault_rifle",
    "silenced_assault_rifle",
];
export const shotgunKillMethodList = [
    "loud_shotgun",
    "shotgun",
    "silenced_shotgun",
];
export const sniperKillMethodList = [
    "loud_sniper_rifle",
    "sniper_rifle",
    "silenced_sniper_rifle",
];
export const largeWeaponsList = [
    ...assaultRifleKillMethodList,
    ...shotgunKillMethodList,
    ...sniperKillMethodList,
];
export const explosiveKillMethodList = [
    "remote_explosive",
    "loud_explosive",
    "impact_explosive",
];

export const uniqueKills = [
    "drowning",
    "falling_object",
    "fall",
    "fire",
    "electrocution",
    "explosion_accident",
    "consumed_poison",
    "injected_poison",
];

export const sodersUniqueKills = [
    "throw_the_heart_in_the_trash",
    "shoot_the_heart",
    "electrocution",
    "explosion",
    "poison_stem_cells",
    "robot_arms",
];

// Paris
const parisMelees = [
    "scissors",
    "screwdriver",
    "letter_opener",
    "fire_axe",
    "kitchen_knife",
    "cleaver",
    "hatchet",
    "battle_axe",
    "saber",
    "fiber_wire",
    "neck_snap",
];
const parisDisguises = [
    "suit",
    "auction_staff",
    "chef",
    "cicada_bodyguard",
    "helmut_kruger",
    "palace_staff",
    "security_guard",
    "sheikh",
    "stylist",
    "tech_crew",
    "vampire_magician",
];

// Sapienza
const sapienzaMelees = [
    "circumcision_knife",
    "amputation_knife",
    "fire_axe",
    "letter_opener",
    "screwdriver",
    "hatchet",
    "kitchen_knife",
    "saber",
    "scissors",
    "combat_knife",
    "folding_knife",
    "old_axe",
    "battle_axe",
    "katana",
    "cleaver",
    "fiber_wire",
    "neck_snap",
];
const sapienzaDisguises = [
    "suit",
    "biolab_security",
    "bodyguard",
    "bohemian",
    "butler",
    "church_staff",
    "cyclist",
    "delivery_man",
    "oscar_lafayette",
    "gardener",
    "green_plumber",
    "hazmat_suit",
    "housekeeper",
    "kitchen_assistant",
    "lab_technician",
    "chef",
    "mansion_security",
    "mansion_staff",
    "plague_doctor",
    "priest",
    "private_detective",
    "red_plumber",
    "roberto_vargas",
    "store_clerk",
    "street_performer",
    "waiter",
];

// Marrakesh
const marrakeshMelees = [
    "screwdriver",
    "kitchen_knife",
    "cleaver",
    "scissors",
    "letter_opener",
    "fire_axe",
    "saber",
    "battle_axe",
    "fiber_wire",
    "neck_snap",
];
const marrakeshDisguises = [
    "suit",
    "bodyguard",
    "cameraman",
    "consulate_intern",
    "consulate_janitor",
    "consulate_security",
    "elite_soldier",
    "food_vendor",
    "fortune_teller",
    "handyman",
    "headmaster",
    "local_printing_crew",
    "masseur",
    "military_officer",
    "military_soldier",
    "prisoner",
    "shopkeeper",
    "waiter",
];

// Bangkok
const bangkokMelees = [
    "hatchet",
    "fire_axe",
    "screwdriver",
    "cleaver",
    "kitchen_knife",
    "letter_opener",
    "katana",
    "sappers_axe",
    "fiber_wire",
    "neck_snap",
];
const bangkokDisguises = [
    "suit",
    "abel_de_silva",
    "exterminator",
    "groundskeeper",
    "hotel_security",
    "hotel_staff",
    "jordan_cross_bodyguard",
    "kitchen_staff",
    "morgans_bodyguard",
    "recording_crew",
    "stalker",
    "waiter",
];

// Colorado
const coloradoMelees = [
    "screwdriver",
    "cleaver",
    "kitchen_knife",
    "old_axe",
    "fiber_wire",
    "neck_snap",
];
const coloradoDisguises = [
    "suit",
    "explosives_specialist",
    "hacker",
    "militia_cook",
    "militia_elite",
    "militia_soldier",
    "militia_spec_ops",
    "militia_technician",
    "point_man",
    "scarecrow",
];

// Hokkaido
const hokkaidoMelees = [
    "fire_axe",
    "scalpel",
    "screwdriver",
    "kitchen_knife",
    "cleaver",
    "katana",
    "scissors",
    "fiber_wire",
    "neck_snap",
];
const hokkaidoDisguises = [
    "suit",
    "baseball_player",
    "bodyguard",
    "chef",
    "chief_surgeon",
    "doctor",
    "handyman",
    "helicopter_pilot",
    "hospital_director",
    "morgue_doctor",
    "motorcyclist",
    "ninja",
    "patient",
    "resort_security",
    "resort_staff",
    "surgeon",
    "amos_dexter",
    "jason_portman",
    "yoga_instructor",
];

// Miami
const miamiMelees = [
    "screwdriver",
    "fire_axe",
    "scissors",
    "kitchen_knife",
    "cleaver",
    "old_axe",
    "amputation_knife",
    "starfish",
    "battle_axe",
    "fiber_wire",
    "neck_snap",
];
const miamiDisguises = [
    "suit",
    "aeon_driver",
    "aeon_mechanic",
    "blue_seed_driver",
    "crashed_kronstadt_driver",
    "event_crew",
    "event_security",
    "florida_man",
    "food_vendor",
    "journalist",
    "kitchen_staff",
    "kowoon_driver",
    "kowoon_mechanic",
    "kronstadt_engineer",
    "kronstadt_mechanic",
    "kronstadt_researcher",
    "kronstadt_security",
    "mascot",
    "medic",
    "moses_lee",
    "pale_rider",
    "race_coordinator",
    "race_marshal",
    "sheikh",
    "sotteraneo_mechanic",
    "street_musician",
    "ted_mendez",
    "thwack_driver",
    "thwack_mechanic",
    "waiter",
];

// Santa Fortuna
const santaFortunaMelees = [
    "screwdriver",
    "kitchen_knife",
    "letter_opener",
    "scissors",
    "cleaver",
    "machete",
    "folding_knife",
    "barber_razor",
    "fiber_wire",
    "neck_snap",
    "sacrificial_knife",
];
const santaFortunaDisguises = [
    "suit",
    "band_member",
    "barman",
    "chef",
    "coca_field_guard",
    "coca_field_worker",
    "construction_worker",
    "drug_lab_worker",
    "elite_guard",
    "gardener",
    "hippie",
    "hippo_whisperer",
    "mansion_guard",
    "mansion_staff",
    "shaman",
    "street_soldier",
    "submarine_crew",
    "submarine_engineer",
    "tattoo_artist",
];

// Mumbai
const mumbaiMelees = [
    "kitchen_knife",
    "beak_staff",
    "old_axe",
    "scissors",
    "screwdriver",
    "barber_razor",
    "fire_axe",
    "amputation_knife",
    "cleaver",
    "folding_knife",
    "letter_opener",
    "saber",
    "fiber_wire",
    "neck_snap",
];
const mumbaiDisguises = [
    "suit",
    "barber",
    "bollywood_bodyguard",
    "bollywood_crew",
    "dancer",
    "elite_thug",
    "food_vendor",
    "holy_man",
    "kashmirian",
    "laundry_foreman",
    "laundry_worker",
    "lead_actor",
    "local_security",
    "metal_worker",
    "painter",
    "queens_bodyguard",
    "queens_guard",
    "tailor",
    "thug",
    "vanyas_servant",
];

// Whittleton Creek
const whittletonCreekMelees = [
    "kitchen_knife",
    "screwdriver",
    "fire_axe",
    "scissors",
    "letter_opener",
    "hatchet",
    "fiber_wire",
    "neck_snap",
];
const whittletonCreekDisguises = [
    "suit",
    "arkian_robes",
    "bbq_owner",
    "cassidy_bodyguard",
    "construction_worker",
    "exterminator",
    "garbage_man",
    "gardener",
    "gunther",
    "james_batty",
    "janus_bodyguard",
    "mailman",
    "nurse",
    "plumber",
    "police_deputy",
    "politician",
    "politicians_assistant",
    "real_estate_broker",
    "server",
    "sheriff_masterson",
    "spencer_green",
];

// Ambrose Island
const ambroseIslandMelees = [
    "garden_fork",
    "starfish",
    "scissors",
    "cleaver",
    "kitchen_knife",
    "meat_fork",
    "letter_opener",
    "kukri_machete",
    "seashell",
    "screwdriver",
    "folding_knife",
    "old_axe",
    "hook",
    "scrap_sword",
    "shears",
    "barber_razor",
    "hobby_knife",
    "jarls_pirate_saber",
    "fiber_wire",
    "neck_snap",
];
const ambroseIslandDisguises = [
    "suit",
    "cook",
    "engineer",
    "hippie",
    "metal_worker",
    "militia_soldier",
    "pirate",
];

// Isle of Sgail
const isleOfSgailMelees = [
    "battle_axe",
    "sappers_axe",
    "broadsword",
    "old_axe",
    "saber",
    "viking_axe",
    "hatchet",
    "scalpel",
    "screwdriver",
    "letter_opener",
    "cleaver",
    "kitchen_knife",
    "fire_axe",
    "circumcision_knife",
    "scissors",
    "katana",
    "starfish",
    "fiber_wire",
    "neck_snap",
    "sacrificial_knife",
];
const isleOfSgailDisguises = [
    "suit",
    "architect",
    "ark_member",
    "blake_nathaniel",
    "burial_robes",
    "butler",
    "castle_staff",
    "chef",
    "custodian",
    "elite_guard",
    "entertainer",
    "event_staff",
    "guard",
    "initiate",
    "jebediah_block",
    "knights_armor",
    "master_of_ceremonies",
    "raider",
];

const newYorkMelees = [
    "letter_opener",
    "screwdriver",
    "fire_axe",
    "scissors",
    "tanto",
    "hobby_knife",
    "burial_dagger",
    "kitchen_knife",
    "antique_carved_knife",
    "folding_knife",
    "fiber_wire",
    "neck_snap",
];
const newYorkDisguises = [
    "suit",
    "bank_robber",
    "bank_teller",
    "fired_banker",
    "high_security_guard",
    "investment_banker",
    "it_worker",
    "janitor",
    "job_applicant",
    "security_guard",
];

// Haven Island
const havenIslandMelees = [
    "barber_razor",
    "scissors",
    "scalpel",
    "machete",
    "folding_knife",
    "screwdriver",
    "starfish",
    "cleaver",
    "kitchen_knife",
    "hatchet",
    "letter_opener",
    "seashell",
    "jarls_pirate_saber",
    "fire_axe",
    "fiber_wire",
    "neck_snap",
];
const havenIslandDisguises = [
    "suit",
    "boat_captain",
    "bodyguard",
    "butler",
    "chef",
    "doctor",
    "gas_suit",
    "lifeguard",
    "masseur",
    "personal_trainer",
    "resort_guard",
    "resort_staff",
    "snorkel_instructor",
    "tech_crew",
    "villa_guard",
    "villa_staff",
    "waiter",
];

// Dubai
const dubaiMelees = [
    "letter_opener",
    "ornate_scimitar",
    "kitchen_knife",
    "screwdriver",
    "fire_axe",
    "cleaver",
    "scissors",
    "folding_knife",
    "fiber_wire",
    "neck_snap",
];
const dubaiDisguises = [
    "suit",
    "art_crew",
    "event_security",
    "event_staff",
    "famous_chef",
    "helicopter_pilot",
    "ingrams_bodyguard",
    "kitchen_staff",
    "maintenance_staff",
    "penthouse_guard",
    "penthouse_staff",
    "skydiving_suit",
    "assassin",
];

// Dartmoor
const dartmoorMelees = [
    "hatchet",
    "shears",
    "folding_knife",
    "garden_fork",
    "screwdriver",
    "unicorn_horn",
    "letter_opener",
    "barber_razor",
    "saber",
    "cleaver",
    "scissors",
    "kitchen_knife",
    "fiber_wire",
    "neck_snap",
];
const dartmoorDisguises = [
    "suit",
    "bodyguard",
    "gardener",
    "lawyer",
    "mansion_guard",
    "mansion_staff",
    "photographer",
    "private_investigator",
    "undertaker",
];

// Berlin
const berlinMelees = [
    "kitchen_knife",
    "screwdriver",
    "fire_axe",
    "hobby_knife",
    "battle_axe",
    "garden_fork",
    "scrap_sword",
    "combat_knife",
    "old_axe",
    "concealable_knife",
    "fiber_wire",
    "neck_snap",
];
const berlinDisguises = [
    "suit",
    "bartender",
    "biker",
    "club_crew",
    "club_security",
    "dealer",
    "delivery_guy",
    "dj",
    "florida_man",
    "rolf",
    "technician",
];

// Chongqing
const chongqingMelees = [
    "screwdriver",
    "fire_axe",
    "tanto",
    "letter_opener",
    "scrap_sword",
    "cleaver",
    "kitchen_knife",
    "scissors",
    "hobby_knife",
    "garden_fork",
    "fiber_wire",
    "neck_snap",
];
const chongqingDisguises = [
    "suit",
    "block_guard",
    "dumpling_cook",
    "facility_analyst",
    "facility_engineer",
    "facility_guard",
    "facility_security",
    "homeless_person",
    "perfect_test_subject",
    "researcher",
    "street_guard",
    "board_member",
];

// Mendoza
const mendozaMelees = [
    "broadsword",
    "jarls_pirate_saber",
    "old_axe",
    "sappers_axe",
    "shears",
    "garden_fork",
    "grape_knife",
    "screwdriver",
    "fire_axe",
    "combat_knife",
    "hatchet",
    "machete",
    "hobby_knife",
    "icicle",
    "kitchen_knife",
    "fiber_wire",
    "neck_snap",
];
const mendozaDisguises = [
    "suit",
    "asado_chef",
    "bodyguard",
    "chief_winemaker",
    "corvo_black",
    "gaucho",
    "head_of_security",
    "lawyer",
    "mercenary",
    "providence_herald",
    "sommelier",
    "tango_musician",
    "waiter",
    "winery_worker",
];

export const SpinMissionTargetsList: SpinMissionTargets = {
    paris: ["viktor_novikov", "dalia_margolis"],
    sapienza: ["silvio_caruso", "francesca_de_santis"],
    marrakesh: ["claus_strandberg", "reza_zaydan"],
    bangkok: ["jordan_cross", "ken_morgan"],
    colorado: ["sean_rose", "ezra_berg", "penelope_graves", "maya_parvati"],
    hokkaido: ["erich_soders", "yuki_yamazaki"],
    miami: ["sierra_knox", "robert_knox"],
    santa_fortuna: ["rico_delgado", "jorge_franco", "andrea_martinez"],
    mumbai: ["dawood_rangan", "vanya_shah", "wazir_kale"],
    whittleton_creek: ["janus", "nolan_cassidy"],
    ambrose_island: ["noel_crest", "sinhi_akka"],
    isle_of_sgail: ["zoe_washington", "sophia_washington"],
    new_york: ["athena_savalas"],
    haven_island: ["tyson_williams", "ljudmila_vetrova", "steven_bradley"],
    dubai: ["carl_ingram", "marcus_stuyvesant"],
    dartmoor: ["alexa_carlisle"],
    berlin: [
        "ica_agent_#1",
        "ica_agent_#2",
        "ica_agent_#3",
        "ica_agent_#4",
        "ica_agent_#5",
    ],
    chongqing: ["hush", "imogen_royce"],
    mendoza: ["don_yates", "tamara_vidal"],
} as const;

export const TargetBannedKillMethodsList: TargetBannedKillMethods = {
    viktor_novikov: ["fire"],
    dalia_margolis: ["fire"],
    silvio_caruso: ["fire", "consumed_poison"],
    francesca_de_santis: ["fire"],
    claus_strandberg: ["falling_object"],
    reza_zaydan: ["drowning", "electrocution"],
    jordan_cross: ["fire"],
    ken_morgan: ["fire"],
    sean_rose: ["consumed_poison", "drowning"],
    ezra_berg: ["electrocution", "consumed_poison", "drowning"],
    penelope_graves: ["drowning", "fire"],
    maya_parvati: ["drowning"],
    erich_soders: [],
    yuki_yamazaki: [],
    sierra_knox: [],
    robert_knox: ["fire"],
    rico_delgado: ["consumed_poison"],
    jorge_franco: ["falling_object"],
    andrea_martinez: ["fire"],
    dawood_rangan: ["fire", "drowning", "consumed_poison", "impact_explosive"],
    vanya_shah: ["consumed_poison", "impact_explosive"],
    wazir_kale: ["fire", "drowning"],
    janus: ["falling_object", "fire"],
    nolan_cassidy: ["fire"],
    noel_crest: [],
    sinhi_akka: [],
    zoe_washington: ["consumed_poison"],
    sophia_washington: ["consumed_poison", "fire"],
    athena_savalas: ["fire"],
    tyson_williams: ["fire", "consumed_poison"],
    ljudmila_vetrova: ["fire", "falling_object"],
    steven_bradley: ["fire", "consumed_poison"],
    carl_ingram: ["consumed_poison", "fire"],
    marcus_stuyvesant: ["consumed_poison", "fire"],
    alexa_carlisle: ["fire"],
    hush: ["fire", "consumed_poison", "impact_explosive"],
    imogen_royce: ["fire", "consumed_poison", "falling_object"],
    don_yates: ["consumed_poison", "fire"],
    tamara_vidal: ["consumed_poison", "falling_object", "fire"],
    "ica_agent_#1": [],
    "ica_agent_#2": [],
    "ica_agent_#3": [],
    "ica_agent_#4": [],
    "ica_agent_#5": [],
};

export const MissionSpinInfoList: MissionSpinOptions = {
    paris: {
        disguises: parisDisguises,
        killMethods: {
            melees: parisMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    sapienza: {
        disguises: sapienzaDisguises,
        killMethods: {
            melees: sapienzaMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    marrakesh: {
        disguises: marrakeshDisguises,
        killMethods: {
            melees: marrakeshMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    bangkok: {
        disguises: bangkokDisguises,
        killMethods: {
            melees: bangkokMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    colorado: {
        disguises: coloradoDisguises,
        killMethods: {
            melees: coloradoMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    hokkaido: {
        disguises: hokkaidoDisguises,
        killMethods: {
            melees: hokkaidoMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    miami: {
        disguises: miamiDisguises,
        killMethods: {
            melees: miamiMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    santa_fortuna: {
        disguises: santaFortunaDisguises,
        killMethods: {
            melees: santaFortunaMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    mumbai: {
        disguises: mumbaiDisguises,
        killMethods: {
            melees: mumbaiMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    whittleton_creek: {
        disguises: whittletonCreekDisguises,
        killMethods: {
            melees: whittletonCreekMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    ambrose_island: {
        disguises: ambroseIslandDisguises,
        killMethods: {
            melees: ambroseIslandMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    isle_of_sgail: {
        disguises: isleOfSgailDisguises,
        killMethods: {
            melees: isleOfSgailMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    new_york: {
        disguises: newYorkDisguises,
        killMethods: {
            melees: newYorkMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    haven_island: {
        disguises: havenIslandDisguises,
        killMethods: {
            melees: havenIslandMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    dubai: {
        disguises: dubaiDisguises,
        killMethods: {
            melees: dubaiMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    dartmoor: {
        disguises: dartmoorDisguises,
        killMethods: {
            melees: dartmoorMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    berlin: {
        disguises: berlinDisguises,
        killMethods: {
            melees: berlinMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    chongqing: {
        disguises: chongqingDisguises,
        killMethods: {
            melees: chongqingMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
    mendoza: {
        disguises: mendozaDisguises,
        killMethods: {
            melees: mendozaMelees,
            weapons: weapons,
            unique_kills: uniqueKills,
        },
    },
};

export const TargetUniqueKillsList: TargetUniqueKills = {
    viktor_novikov: [],
    dalia_margolis: [],
    silvio_caruso: [
        "shoot_silvio_through_the_telescope",
        "destroy_the_seaplane",
    ],
    francesca_de_santis: [],
    claus_strandberg: [],
    reza_zaydan: [],
    jordan_cross: [],
    ken_morgan: [],
    sean_rose: ["explosive_watch_battery"],
    ezra_berg: [],
    penelope_graves: [],
    maya_parvati: [],
    erich_soders: [
        "throw_the_heart_in_the_trash",
        "shoot_the_heart",
        "electrocution",
        "explosion",
        "poison_stem_cells",
        "robot_arms",
    ],
    yuki_yamazaki: ["overheat_the_sauna"],
    sierra_knox: ["shoot_the_car"],
    robert_knox: [],
    rico_delgado: ["feed_to_the_hippo"],
    jorge_franco: ["dump_in_the_cocaine_machine"],
    andrea_martinez: [],
    dawood_rangan: [],
    vanya_shah: [],
    wazir_kale: [],
    janus: [],
    nolan_cassidy: [],
    noel_crest: [],
    sinhi_akka: [],
    zoe_washington: [],
    sophia_washington: [],
    athena_savalas: ["athena_savalas_award"],
    tyson_williams: [],
    ljudmila_vetrova: [],
    steven_bradley: ["explosive_on_water_scooter"],
    carl_ingram: [],
    marcus_stuyvesant: [],
    alexa_carlisle: [],
    "ica_agent_#1": [],
    "ica_agent_#2": [],
    "ica_agent_#3": [],
    "ica_agent_#4": [],
    "ica_agent_#5": [],
    hush: [],
    imogen_royce: [],
    don_yates: [],
    tamara_vidal: [],
};

export const SeasonOneMissions: Mission[] = [
    "paris",
    "sapienza",
    "marrakesh",
    "bangkok",
    "colorado",
    "hokkaido",
];

export const SeasonTwoMissions: Mission[] = [
    "miami",
    "santa_fortuna",
    "mumbai",
    "whittleton_creek",
    "ambrose_island",
    "isle_of_sgail",
    "new_york",
    "haven_island",
];

export const SeasonThreeMissions: Mission[] = [
    "dubai",
    "dartmoor",
    "berlin",
    "chongqing",
    "mendoza",
];

export const MissionPoolOptionsList: MissionPoolOptions = {
    paris: false,
    sapienza: false,
    marrakesh: false,
    bangkok: false,
    colorado: false,
    hokkaido: false,
    miami: false,
    santa_fortuna: false,
    mumbai: false,
    whittleton_creek: false,
    ambrose_island: false,
    isle_of_sgail: false,
    new_york: false,
    haven_island: false,
    dubai: false,
    dartmoor: false,
    berlin: false,
    chongqing: false,
    mendoza: false,
};

export const SeasonPoolSelectedList: SeasonPoolSelected = {
    season_1: false,
    season_2: false,
    season_3: false,
};

export const KillMethodOptions = [
    "pistol",
    "loud_pistol",
    "silenced_pistol",
    "sniper_rifle",
    "loud_sniper_rifle",
    "silenced_sniper_rifle",
    "assault_rifle",
    "loud_assault_rifle",
    "silenced_assault_rifle",
    "smg",
    "loud_smg",
    "silenced_smg",
    "shotgun",
    "loud_shotgun",
    "silenced_shotgun",
    "remote_explosive",
    "loud_explosive",
    "impact_explosive",
    "drowning",
    "falling_object",
    "fall",
    "fire",
    "electrocution",
    "explosion_accident",
    "consumed_poison",
    "injected_poison",
    "shoot_silvio_through_the_telescope",
    "explosive_watch_battery",
    "throw_the_heart_in_the_trash",
    "shoot_the_heart",
    "electrocution",
    "explosion",
    "poison_stem_cells",
    "robot_arms",
    "shoot_the_car",
    "athena_savalas_award",
    "explosive_on_water_scooter",
    "amputation_knife",
    "antique_carved_knife",
    "barber_razor",
    "battle_axe",
    "beak_staff",
    "broadsword",
    "burial_dagger",
    "circumcision_knife",
    "cleaver",
    "combat_knife",
    "concealable_knife",
    "fiber_wire",
    "fire_axe",
    "folding_knife",
    "garden_fork",
    "grape_knife",
    "hatchet",
    "hobby_knife",
    "hook",
    "icicle",
    "jarls_pirate_saber",
    "katana",
    "kitchen_knife",
    "kukri_machete",
    "letter_opener",
    "machete",
    "meat_fork",
    "neck_snap",
    "old_axe",
    "ornate_scimitar",
    "saber",
    "sappers_axe",
    "scalpel",
    "scissors",
    "scrap_sword",
    "screwdriver",
    "seashell",
    "shears",
    "starfish",
    "tanto",
    "unicorn_horn",
    "viking_axe",
];

export const MissionDisguisesList: MissionDisguises = {
    paris: parisDisguises,
    sapienza: sapienzaDisguises,
    marrakesh: marrakeshDisguises,
    bangkok: bangkokDisguises,
    colorado: coloradoDisguises,
    hokkaido: hokkaidoDisguises,
    miami: miamiDisguises,
    santa_fortuna: santaFortunaDisguises,
    mumbai: mumbaiDisguises,
    whittleton_creek: whittletonCreekDisguises,
    ambrose_island: ambroseIslandDisguises,
    isle_of_sgail: isleOfSgailDisguises,
    new_york: newYorkDisguises,
    haven_island: havenIslandDisguises,
    dubai: dubaiDisguises,
    dartmoor: dartmoorDisguises,
    berlin: berlinDisguises,
    chongqing: chongqingDisguises,
    mendoza: mendozaDisguises,
};

export const SpinInfoIdMap: { [key: string]: string } = {
    "00": "pistol",
    pistol: "00",
    "01": "loud_pistol",
    loud_pistol: "01",
    "02": "silenced_pistol",
    silenced_pistol: "02",
    "03": "sniper_rifle",
    sniper_rifle: "03",
    "04": "loud_sniper_rifle",
    loud_sniper_rifle: "04",
    "05": "silenced_sniper_rifle",
    silenced_sniper_rifle: "05",
    "06": "assault_rifle",
    assault_rifle: "06",
    "07": "loud_assault_rifle",
    loud_assault_rifle: "07",
    "08": "silenced_assault_rifle",
    silenced_assault_rifle: "08",
    "09": "smg",
    smg: "09",
    "0a": "loud_smg",
    loud_smg: "0a",
    "0b": "silenced_smg",
    silenced_smg: "0b",
    "0c": "shotgun",
    shotgun: "0c",
    "0d": "loud_shotgun",
    loud_shotgun: "0d",
    "0e": "silenced_shotgun",
    silenced_shotgun: "0e",
    "0f": "remote_explosive",
    remote_explosive: "0f",
    "0g": "loud_explosive",
    loud_explosive: "0g",
    "0h": "impact_explosive",
    impact_explosive: "0h",
    "0i": "drowning",
    drowning: "0i",
    "0j": "falling_object",
    falling_object: "0j",
    "0k": "fall",
    fall: "0k",
    "0l": "fire",
    fire: "0l",
    "0m": "electrocution",
    electrocution: "0m",
    "0n": "explosion_accident",
    explosion_accident: "0n",
    "0o": "consumed_poison",
    consumed_poison: "0o",
    "0p": "injected_poison",
    injected_poison: "0p",
    "0q": "shoot_silvio_through_the_telescope",
    shoot_silvio_through_the_telescope: "0q",
    "0r": "explosive_watch_battery",
    explosive_watch_battery: "0r",
    "0s": "throw_the_heart_in_the_trash",
    throw_the_heart_in_the_trash: "0s",
    "0t": "shoot_the_heart",
    shoot_the_heart: "0t",
    "0v": "explosion",
    explosion: "0v",
    "0w": "poison_stem_cells",
    poison_stem_cells: "0w",
    "0x": "robot_arms",
    robot_arms: "0x",
    "0y": "shoot_the_car",
    shoot_the_car: "0y",
    "0z": "athena_savalas_award",
    athena_savalas_award: "0z",
    "10": "explosive_on_water_scooter",
    explosive_on_water_scooter: "10",
    "11": "amputation_knife",
    amputation_knife: "11",
    "12": "antique_carved_knife",
    antique_carved_knife: "12",
    "13": "barber_razor",
    barber_razor: "13",
    "14": "battle_axe",
    battle_axe: "14",
    "15": "beak_staff",
    beak_staff: "15",
    "16": "broadsword",
    broadsword: "16",
    "17": "burial_dagger",
    burial_dagger: "17",
    "18": "circumcision_knife",
    circumcision_knife: "18",
    "19": "cleaver",
    cleaver: "19",
    "1a": "combat_knife",
    combat_knife: "1a",
    "1b": "concealable_knife",
    concealable_knife: "1b",
    "1c": "fiber_wire",
    fiber_wire: "1c",
    "1d": "fire_axe",
    fire_axe: "1d",
    "1e": "folding_knife",
    folding_knife: "1e",
    "1f": "garden_fork",
    garden_fork: "1f",
    "1g": "grape_knife",
    grape_knife: "1g",
    "1h": "hatchet",
    hatchet: "1h",
    "1i": "hobby_knife",
    hobby_knife: "1i",
    "1j": "hook",
    hook: "1j",
    "1k": "icicle",
    icicle: "1k",
    "1l": "jarls_pirate_saber",
    jarls_pirate_saber: "1l",
    "1m": "katana",
    katana: "1m",
    "1n": "kitchen_knife",
    kitchen_knife: "1n",
    "1o": "kukri_machete",
    kukri_machete: "1o",
    "1p": "letter_opener",
    letter_opener: "1p",
    "1q": "machete",
    machete: "1q",
    "1r": "meat_fork",
    meat_fork: "1r",
    "1s": "neck_snap",
    neck_snap: "1s",
    "1t": "old_axe",
    old_axe: "1t",
    "1u": "ornate_scimitar",
    ornate_scimitar: "1u",
    "1v": "saber",
    saber: "1v",
    "1w": "sappers_axe",
    sappers_axe: "1w",
    "1x": "scalpel",
    scalpel: "1x",
    "1y": "scissors",
    scissors: "1y",
    "1z": "scrap_sword",
    scrap_sword: "1z",
    "20": "screwdriver",
    screwdriver: "20",
    "21": "seashell",
    seashell: "21",
    "22": "shears",
    shears: "22",
    "23": "starfish",
    starfish: "23",
    "24": "tanto",
    tanto: "24",
    "25": "unicorn_horn",
    unicorn_horn: "25",
    "26": "viking_axe",
    viking_axe: "26",
    "27": "suit",
    suit: "27",
    "28": "auction_staff",
    auction_staff: "28",
    "29": "chef",
    chef: "29",
    "2a": "cicada_bodyguard",
    cicada_bodyguard: "2a",
    "2b": "helmut_kruger",
    helmut_kruger: "2b",
    "2c": "palace_staff",
    palace_staff: "2c",
    "2d": "security_guard",
    security_guard: "2d",
    "2e": "sheikh",
    sheikh: "2e",
    "2f": "stylist",
    stylist: "2f",
    "2g": "tech_crew",
    tech_crew: "2g",
    "2h": "vampire_magician",
    vampire_magician: "2h",
    "2j": "biolab_security",
    biolab_security: "2j",
    "2k": "bodyguard",
    bodyguard: "2k",
    "2l": "bohemian",
    bohemian: "2l",
    "2m": "butler",
    butler: "2m",
    "2n": "church_staff",
    church_staff: "2n",
    "2o": "cyclist",
    cyclist: "2o",
    "2p": "delivery_man",
    delivery_man: "2p",
    "2q": "oscar_lafayette",
    oscar_lafayette: "2q",
    "2r": "gardener",
    gardener: "2r",
    "2s": "green_plumber",
    green_plumber: "2s",
    "2t": "hazmat_suit",
    hazmat_suit: "2t",
    "2u": "housekeeper",
    housekeeper: "2u",
    "2v": "kitchen_assistant",
    kitchen_assistant: "2v",
    "2w": "lab_technician",
    lab_technician: "2w",
    "2y": "mansion_security",
    mansion_security: "2y",
    "2z": "mansion_staff",
    mansion_staff: "2z",
    "30": "plague_doctor",
    plague_doctor: "30",
    "31": "priest",
    priest: "31",
    "32": "private_detective",
    private_detective: "32",
    "33": "red_plumber",
    red_plumber: "33",
    "34": "roberto_vargas",
    roberto_vargas: "34",
    "35": "store_clerk",
    store_clerk: "35",
    "36": "street_performer",
    street_performer: "36",
    "37": "waiter",
    waiter: "37",
    "3a": "cameraman",
    cameraman: "3a",
    "3b": "consulate_intern",
    consulate_intern: "3b",
    "3c": "consulate_janitor",
    consulate_janitor: "3c",
    "3d": "consulate_security",
    consulate_security: "3d",
    "3e": "elite_soldier",
    elite_soldier: "3e",
    "3f": "food_vendor",
    food_vendor: "3f",
    "3g": "fortune_teller",
    fortune_teller: "3g",
    "3h": "handyman",
    handyman: "3h",
    "3i": "headmaster",
    headmaster: "3i",
    "3j": "local_printing_crew",
    local_printing_crew: "3j",
    "3k": "masseur",
    masseur: "3k",
    "3l": "military_officer",
    military_officer: "3l",
    "3m": "military_soldier",
    military_soldier: "3m",
    "3n": "prisoner",
    prisoner: "3n",
    "3o": "shopkeeper",
    shopkeeper: "3o",
    "3r": "abel_de_silva",
    abel_de_silva: "3r",
    "3s": "exterminator",
    exterminator: "3s",
    "3t": "groundskeeper",
    groundskeeper: "3t",
    "3u": "hotel_security",
    hotel_security: "3u",
    "3v": "hotel_staff",
    hotel_staff: "3v",
    "3w": "jordan_cross_bodyguard",
    jordan_cross_bodyguard: "3w",
    "3x": "kitchen_staff",
    kitchen_staff: "3x",
    "3y": "morgans_bodyguard",
    morgans_bodyguard: "3y",
    "3z": "recording_crew",
    recording_crew: "3z",
    "40": "stalker",
    stalker: "40",
    "43": "explosives_specialist",
    explosives_specialist: "43",
    "44": "hacker",
    hacker: "44",
    "45": "militia_cook",
    militia_cook: "45",
    "46": "militia_elite",
    militia_elite: "46",
    "47": "militia_soldier",
    militia_soldier: "47",
    "48": "militia_spec_ops",
    militia_spec_ops: "48",
    "49": "militia_technician",
    militia_technician: "49",
    "4a": "point_man",
    point_man: "4a",
    "4b": "scarecrow",
    scarecrow: "4b",
    "4d": "baseball_player",
    baseball_player: "4d",
    "4g": "chief_surgeon",
    chief_surgeon: "4g",
    "4h": "doctor",
    doctor: "4h",
    "4j": "helicopter_pilot",
    helicopter_pilot: "4j",
    "4k": "hospital_director",
    hospital_director: "4k",
    "4l": "morgue_doctor",
    morgue_doctor: "4l",
    "4m": "motorcyclist",
    motorcyclist: "4m",
    "4n": "ninja",
    ninja: "4n",
    "4o": "patient",
    patient: "4o",
    "4p": "resort_security",
    resort_security: "4p",
    "4q": "resort_staff",
    resort_staff: "4q",
    "4r": "surgeon",
    surgeon: "4r",
    "4s": "amos_dexter",
    amos_dexter: "4s",
    "4t": "jason_portman",
    jason_portman: "4t",
    "4u": "yoga_instructor",
    yoga_instructor: "4u",
    "4w": "aeon_driver",
    aeon_driver: "4w",
    "4x": "aeon_mechanic",
    aeon_mechanic: "4x",
    "4y": "blue_seed_driver",
    blue_seed_driver: "4y",
    "4z": "crashed_kronstadt_driver",
    crashed_kronstadt_driver: "4z",
    "50": "event_crew",
    event_crew: "50",
    "51": "event_security",
    event_security: "51",
    "52": "florida_man",
    florida_man: "52",
    "54": "journalist",
    journalist: "54",
    "56": "kowoon_driver",
    kowoon_driver: "56",
    "57": "kowoon_mechanic",
    kowoon_mechanic: "57",
    "58": "kronstadt_engineer",
    kronstadt_engineer: "58",
    "59": "kronstadt_mechanic",
    kronstadt_mechanic: "59",
    "5a": "kronstadt_researcher",
    kronstadt_researcher: "5a",
    "5b": "kronstadt_security",
    kronstadt_security: "5b",
    "5c": "mascot",
    mascot: "5c",
    "5d": "medic",
    medic: "5d",
    "5e": "moses_lee",
    moses_lee: "5e",
    "5f": "pale_rider",
    pale_rider: "5f",
    "5g": "race_coordinator",
    race_coordinator: "5g",
    "5h": "race_marshal",
    race_marshal: "5h",
    "5j": "sotteraneo_mechanic",
    sotteraneo_mechanic: "5j",
    "5k": "street_musician",
    street_musician: "5k",
    "5l": "ted_mendez",
    ted_mendez: "5l",
    "5m": "thwack_driver",
    thwack_driver: "5m",
    "5n": "thwack_mechanic",
    thwack_mechanic: "5n",
    "5q": "band_member",
    band_member: "5q",
    "5r": "barman",
    barman: "5r",
    "5t": "coca_field_guard",
    coca_field_guard: "5t",
    "5u": "coca_field_worker",
    coca_field_worker: "5u",
    "5v": "construction_worker",
    construction_worker: "5v",
    "5w": "drug_lab_worker",
    drug_lab_worker: "5w",
    "5x": "elite_guard",
    elite_guard: "5x",
    "5z": "hippie",
    hippie: "5z",
    "60": "hippo_whisperer",
    hippo_whisperer: "60",
    "61": "mansion_guard",
    mansion_guard: "61",
    "63": "shaman",
    shaman: "63",
    "64": "street_soldier",
    street_soldier: "64",
    "65": "submarine_crew",
    submarine_crew: "65",
    "66": "submarine_engineer",
    submarine_engineer: "66",
    "67": "tattoo_artist",
    tattoo_artist: "67",
    "69": "barber",
    barber: "69",
    "6a": "bollywood_bodyguard",
    bollywood_bodyguard: "6a",
    "6b": "bollywood_crew",
    bollywood_crew: "6b",
    "6c": "dancer",
    dancer: "6c",
    "6d": "elite_thug",
    elite_thug: "6d",
    "6f": "holy_man",
    holy_man: "6f",
    "6g": "kashmirian",
    kashmirian: "6g",
    "6h": "laundry_foreman",
    laundry_foreman: "6h",
    "6i": "laundry_worker",
    laundry_worker: "6i",
    "6j": "lead_actor",
    lead_actor: "6j",
    "6k": "local_security",
    local_security: "6k",
    "6l": "metal_worker",
    metal_worker: "6l",
    "6m": "painter",
    painter: "6m",
    "6n": "queens_bodyguard",
    queens_bodyguard: "6n",
    "6o": "queens_guard",
    queens_guard: "6o",
    "6p": "tailor",
    tailor: "6p",
    "6q": "thug",
    thug: "6q",
    "6r": "vanyas_servant",
    vanyas_servant: "6r",
    "6t": "arkian_robes",
    arkian_robes: "6t",
    "6u": "bbq_owner",
    bbq_owner: "6u",
    "6v": "cassidy_bodyguard",
    cassidy_bodyguard: "6v",
    "6y": "garbage_man",
    garbage_man: "6y",
    "70": "gunther",
    gunther: "70",
    "71": "james_batty",
    james_batty: "71",
    "72": "janus_bodyguard",
    janus_bodyguard: "72",
    "73": "mailman",
    mailman: "73",
    "74": "nurse",
    nurse: "74",
    "75": "plumber",
    plumber: "75",
    "76": "police_deputy",
    police_deputy: "76",
    "77": "politician",
    politician: "77",
    "78": "politicians_assistant",
    politicians_assistant: "78",
    "79": "real_estate_broker",
    real_estate_broker: "79",
    "7a": "server",
    server: "7a",
    "7b": "sheriff_masterson",
    sheriff_masterson: "7b",
    "7c": "spencer_green",
    spencer_green: "7c",
    "7e": "cook",
    cook: "7e",
    "7f": "engineer",
    engineer: "7f",
    "7j": "pirate",
    pirate: "7j",
    "7l": "architect",
    architect: "7l",
    "7m": "ark_member",
    ark_member: "7m",
    "7n": "blake_nathaniel",
    blake_nathaniel: "7n",
    "7o": "burial_robes",
    burial_robes: "7o",
    "7q": "castle_staff",
    castle_staff: "7q",
    "7s": "custodian",
    custodian: "7s",
    "7u": "entertainer",
    entertainer: "7u",
    "7v": "event_staff",
    event_staff: "7v",
    "7w": "guard",
    guard: "7w",
    "7x": "initiate",
    initiate: "7x",
    "7y": "jebediah_block",
    jebediah_block: "7y",
    "7z": "knights_armor",
    knights_armor: "7z",
    "80": "master_of_ceremonies",
    master_of_ceremonies: "80",
    "81": "raider",
    raider: "81",
    "83": "bank_robber",
    bank_robber: "83",
    "84": "bank_teller",
    bank_teller: "84",
    "85": "fired_banker",
    fired_banker: "85",
    "86": "high_security_guard",
    high_security_guard: "86",
    "87": "investment_banker",
    investment_banker: "87",
    "88": "it_worker",
    it_worker: "88",
    "89": "janitor",
    janitor: "89",
    "8a": "job_applicant",
    job_applicant: "8a",
    "8d": "boat_captain",
    boat_captain: "8d",
    "8i": "gas_suit",
    gas_suit: "8i",
    "8j": "lifeguard",
    lifeguard: "8j",
    "8l": "personal_trainer",
    personal_trainer: "8l",
    "8m": "resort_guard",
    resort_guard: "8m",
    "8o": "snorkel_instructor",
    snorkel_instructor: "8o",
    "8q": "villa_guard",
    villa_guard: "8q",
    "8r": "villa_staff",
    villa_staff: "8r",
    "8u": "art_crew",
    art_crew: "8u",
    "8x": "famous_chef",
    famous_chef: "8x",
    "8z": "ingrams_bodyguard",
    ingrams_bodyguard: "8z",
    "91": "maintenance_staff",
    maintenance_staff: "91",
    "92": "penthouse_guard",
    penthouse_guard: "92",
    "93": "penthouse_staff",
    penthouse_staff: "93",
    "94": "skydiving_suit",
    skydiving_suit: "94",
    "95": "assassin",
    assassin: "95",
    "99": "lawyer",
    lawyer: "99",
    "9c": "photographer",
    photographer: "9c",
    "9d": "private_investigator",
    private_investigator: "9d",
    "9e": "undertaker",
    undertaker: "9e",
    "9g": "bartender",
    bartender: "9g",
    "9h": "biker",
    biker: "9h",
    "9i": "club_crew",
    club_crew: "9i",
    "9j": "club_security",
    club_security: "9j",
    "9k": "dealer",
    dealer: "9k",
    "9l": "delivery_guy",
    delivery_guy: "9l",
    "9m": "dj",
    dj: "9m",
    "9o": "rolf",
    rolf: "9o",
    "9p": "technician",
    technician: "9p",
    "9r": "block_guard",
    block_guard: "9r",
    "9s": "dumpling_cook",
    dumpling_cook: "9s",
    "9t": "facility_analyst",
    facility_analyst: "9t",
    "9u": "facility_engineer",
    facility_engineer: "9u",
    "9v": "facility_guard",
    facility_guard: "9v",
    "9w": "facility_security",
    facility_security: "9w",
    "9x": "homeless_person",
    homeless_person: "9x",
    "9y": "perfect_test_subject",
    perfect_test_subject: "9y",
    "9z": "researcher",
    researcher: "9z",
    a0: "street_guard",
    street_guard: "a0",
    a1: "board_member",
    board_member: "a1",
    a3: "asado_chef",
    asado_chef: "a3",
    a5: "chief_winemaker",
    chief_winemaker: "a5",
    a6: "corvo_black",
    corvo_black: "a6",
    a7: "gaucho",
    gaucho: "a7",
    a8: "head_of_security",
    head_of_security: "a8",
    aa: "mercenary",
    mercenary: "aa",
    ab: "providence_herald",
    providence_herald: "ab",
    ac: "sommelier",
    sommelier: "ac",
    ad: "tango_musician",
    tango_musician: "ad",
    af: "winery_worker",
    winery_worker: "af",
    ag: "paris",
    paris: "ag",
    ah: "sapienza",
    sapienza: "ah",
    ai: "marrakesh",
    marrakesh: "ai",
    aj: "bangkok",
    bangkok: "aj",
    ak: "colorado",
    colorado: "ak",
    al: "hokkaido",
    hokkaido: "al",
    am: "miami",
    miami: "am",
    an: "santa_fortuna",
    santa_fortuna: "an",
    ao: "mumbai",
    mumbai: "ao",
    ap: "whittleton_creek",
    whittleton_creek: "ap",
    aq: "ambrose_island",
    ambrose_island: "aq",
    ar: "isle_of_sgail",
    isle_of_sgail: "ar",
    as: "new_york",
    new_york: "as",
    at: "haven_island",
    haven_island: "at",
    au: "dubai",
    dubai: "au",
    av: "dartmoor",
    dartmoor: "av",
    aw: "berlin",
    berlin: "aw",
    ax: "chongqing",
    chongqing: "ax",
    ay: "mendoza",
    mendoza: "ay",
    az: "sacrificial_knife",
    sacrificial_knife: "az",
    b0: "any",
    any: "b0",
    b1: "destroy_the_seaplane",
    destroy_the_seaplane: "b1",
    b2: "overheat_the_sauna",
    overheat_the_sauna: "b2",
    feed_to_the_hippo: "b3",
    b3: "feed_to_the_hippo",
    dump_in_the_cocaine_machine: "b4",
    b4: "dump_in_the_cocaine_machine",
} as const;

export const Melees = [
    ...parisMelees,
    ...sapienzaMelees,
    ...marrakeshMelees,
    ...bangkokMelees,
    ...coloradoMelees,
    ...hokkaidoMelees,
    ...miamiMelees,
    ...santaFortunaMelees,
    ...mumbaiMelees,
    ...whittletonCreekMelees,
    ...ambroseIslandMelees,
    ...isleOfSgailMelees,
    ...newYorkMelees,
    ...havenIslandMelees,
    ...dubaiMelees,
    ...dartmoorMelees,
    ...berlinMelees,
    ...chongqingMelees,
    ...mendozaMelees,
];
